### ISSUE TITLE
RGB vs RGBA Conflict

### ISSUE THREAD

**Issue by FiretronP75** [pixunil/cinnamon-applet-system-monitor#13] opened 2015-09-21 21:21 UTC
The applet expects colors to be in rgba, but when you change a color, it is set as rgb. This causes the new color to not show at all, and causes the applet to crash at next start up. I diagnosed the issue by comparing config exports. If you export your color changes, and manually change the JSON data to have rgba values instead of rgb, then import it, it then works.

**Comment by pixunil** [comment] 2015-09-25 20:05
Did you checked da5f554603ade5b2835d34066e1031a4d0f3a75d? It works for me, and I plan a release soon.

**Comment by pixunil** [comment] 2015-10-01 15:27
In release [3.9](https://github.com/pixunil/cinnamon-applet-system-monitor/releases/tag/3.9), closing it because can not reproduce it.

**Closed by pixunil** 2015-10-01 15:27 UTC
